# Generated by Django 5.1.2 on 2024-11-08 08:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='headline',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date held'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='edited',
            field=models.BinaryField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
