# Generated by Django 5.1.2 on 2024-11-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_hub', '0002_announcement_headline_event_name_event_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(),
        ),
    ]
