# Generated by Django 5.1.2 on 2024-11-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_hub', '0003_alter_announcement_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('avatar_url', models.CharField(max_length=200)),
            ],
        ),
    ]
