# Generated by Django 5.1.2 on 2024-11-09 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_hub', '0005_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
